"""add vote score

Revision ID: 6f0939a7c096
Revises: cf2ea66ba498
Create Date: 2023-07-17 19:05:27.272016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0939a7c096'
down_revision = 'cf2ea66ba498'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('vote_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'vote_score')
    # ### end Alembic commands ###
