"""change restaurant_id to int

Revision ID: cf2ea66ba498
Revises: 3e1d7d05d1a7
Create Date: 2023-07-15 15:07:44.089580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2ea66ba498'
down_revision = '3e1d7d05d1a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
