"""add voter table

Revision ID: 296269197d0d
Revises: f1786fe60ad2
Create Date: 2023-07-15 13:10:13.733843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296269197d0d'
down_revision = 'f1786fe60ad2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voter_email'), 'voter', ['email'], unique=True)
    op.create_index(op.f('ix_voter_id'), 'voter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voter_id'), table_name='voter')
    op.drop_index(op.f('ix_voter_email'), table_name='voter')
    op.drop_table('voter')
    # ### end Alembic commands ###
