"""add restaurant table

Revision ID: f1786fe60ad2
Revises: 
Create Date: 2023-07-15 13:08:31.189130

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'f1786fe60ad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_id'), 'restaurant', ['id'], unique=False)
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_id'), table_name='restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
